version: '3'
services:
  web:
    build:
      context: .
      dockerfile: dockerfile-prod
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./blog:/blog
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data