version: '3'
services:
  web:
    build: .
    command: ls /blog
    volumes:
      - .:/blog
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./blog/tmp/db:/var/lib/postgresql/datadco